name: ci 
on:
  push:
    branches:
      - master 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # Add permission for GitHub Pages
      id-token: write   # Add permission for GitHub Pages deployment

    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get update && sudo apt-get install -y libcairo2-dev libxml2-dev libxslt-dev
      - run: pip install -r .github/scripts/requirements.txt
      - run: pip install -r .github/site/requirements.txt
      # New steps start here
      - name: Generate and update TOC, generate and config other things
        run: |
          python .github/scripts/workflows/build_documents.py
      - name: Commit changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update for modify contents" && git push) || true 
      - name: Prepare site
        run: .github/site/prepare_site.sh
      - run: mkdocs gh-deploy --force

      # - name: Run publish script
      #   env:
      #     PUBLISHER_API_KEY: ${{ secrets.PUBLISHER_API_KEY }}
      #     PUBLISH_AS_DRAFT: 'true'  # Or 'false' if you want to publish directly
      #   run: |
      #     python .github/manage/publish.py
      

      # - name: Create docs directory
      #   run: |
      #     mkdir -p docs
      #     cp -r .github docs/
      #     cp README.md docs/
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: 'docs'
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4
